name: Build and Draft Release Tweak

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Tweak
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v6
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install make ldid dpkg

      - name: Set PATH environment variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        id: theos
        uses: actions/cache@v5
        env:
          cache-name: theos_cache_13c2237
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v6
        with:
          repository: theos/theos
          ref: 13c22376b5d83ff759c1993de0a861e673aa522b
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Clone YouTubeHeader
        run: |
          if [ -d "$THEOS/include/YouTubeHeader" ]; then
            cd $THEOS/include/YouTubeHeader && git pull
          else
            cd $THEOS/include && git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi
          rm -rf "$THEOS/include/YTHeaders"
          cp -r "$THEOS/include/YouTubeHeader" "$THEOS/include/YTHeaders"

      - name: Build Package
        run: |
          cd main && make clean package DEBUG=0 FINALPACKAGE=1

      - name: Extract Values
        run: |
          NAME=$(grep '^Name:' main/control | cut -d ' ' -f 2)
          echo "NAME=$NAME" >> $GITHUB_ENV
          PACKAGE=$(grep '^Package:' main/control | cut -d ' ' -f 2)
          VERSION=$(grep '^Version:' main/control | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          ROOTLESS_DEB_FILE_NAME="${PACKAGE}_${VERSION}_iphoneos-arm64.deb"
          echo "ROOTLESS_DEB_FILE_NAME=$ROOTLESS_DEB_FILE_NAME" >> $GITHUB_ENV

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.VERSION }}
          files: |
            main/packages/${{ env.ROOTLESS_DEB_FILE_NAME }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true

      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
